### ISSUE TITLE
`key` not used during update

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/bedrock-ledger-storage-mongodb#11]
There's a loop over `operation.changes` but `key` is not used:

https://github.com/digitalbazaar/bedrock-ledger-storage-mongodb/blob/cm4/lib/ledgerBlockStorage.js#L535-L545

Either the loop is invalid or `key` needs to be used.

**Comment by mattcollier** [comment]
This was addressed during promises conversion.
