### ISSUE TITLE
Ledger IDs not being recorded properly in `ledger` collection

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-ledger-storage-mongodb#2]
Here's a sample of a `ledger` document after running the test suite in `bedrock-ledger-node`
```
{
    "_id": ObjectID("59811171c0fc2dc224f2717f"),
    "id": "urn:uuid:c65b0a4e-eb4f-4f2e-ad6b-fe49d81d44fb",
    "ledger": {
        "id": "urn:uuid:c65b0a4e-eb4f-4f2e-ad6b-fe49d81d44fb",
        "ledger": null,
        "eventCollection": "c65b0a4e-eb4f-4f2e-ad6b-fe49d81d44fb-event",
        "blockCollection": "c65b0a4e-eb4f-4f2e-ad6b-fe49d81d44fb-block",
        "stateMachineCollection": "c65b0a4e-eb4f-4f2e-ad6b-fe49d81d44fb-state-machine"
    },
    "meta": {
        "created": 1501630833306,
        "updated": 1501630833306
    }
}
``` 

This issue likely does not surface in the test suite since we are typically creating one ledger at a time.

**Comment by dlongley** [comment]
Potentially addressed via: https://github.com/digitalbazaar/bedrock-ledger-storage-mongodb/commit/e2a1986200c923cbdd3ece4885d9f7d740ed4d7c

**Comment by mattcollier** [comment]
The `ledger` property has been removed from the record via https://github.com/digitalbazaar/bedrock-ledger-storage-mongodb/commit/d8ab3fe593e96fd67941894693b628f7ef9e86fb
