### ISSUE TITLE
Corner case related to eventHash uniqueness

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-ledger-storage-mongodb#22]
Below is a sample event from a Continuity ledger.  When this event was hashed, it included an `operationHash` property which is an array of hashes for operations that have been assigned to this event.  `operationHash` is deleted from the event before it goes into storage.  

Operations with the same hash are allowed.  In the instance that two events are created with the same `parentHash` and `treeHash` (these two values are always identical for a all `WebLedgerOperationEvent`s) and also both include only a single operation which also has the same hash, then a `DuplicateError` occurs.

In the case of Continuity which is responsible for adding the `parentHash` and `treeHash` properties, this issue would be exceedingly rare.  But a minimal `WebLedgerOperationEvent` is only three properites: '@context', type, and operationHash

Solutions that come to mind are: adding a nonce (id?) or a high resolution timestamp to `WebLedgerOperationEvent`s.

Depending on what the solution is, it may be good to get this addressed sooner rather than later.

```
{
    "_id": ObjectID("5b1974ccca45e167a00a34d6"),
    "eventHash": "d+mffi7s7XzVMvomQnPxl/m2K5RR7fTLjQ0K5sEHcUY=",
    "event": {
        "@context": "https://w3id.org/webledger/v1",
        "type": "WebLedgerOperationEvent",
        "parentHash": [
            "ni:///sha-256;uco9xdKWaWAhafj6goLzv5GJ9qMEci0FklMBzOHZNP8"
        ],
        "treeHash": "ni:///sha-256;uco9xdKWaWAhafj6goLzv5GJ9qMEci0FklMBzOHZNP8"
    },
    "meta": {
        "continuity2017": {
            "creator": "https://bedrock.local:18443/consensus/continuity2017/voters/D1dhMwR1SBpkvAUA6k3iVg6itBg6WfSeunpcDBDTMLah",
            "type": "r"
        },
        "eventHash": "ni:///sha-256;w0g0z1Hcd_TsT6TnEoyFJSbjavdU47ifa11T6hQ9ORc",
        "created": 1528394956133,
        "updated": 1528394956133
    }
}
```

**Comment by dlongley** [comment]
Can we just ignore the DuplicateError? What harm would that cause?

**Comment by mattcollier** [comment]
As it happens, in the principle place I think this would be important we are already ignoring `DuplicateError`.  https://github.com/digitalbazaar/bedrock-ledger-consensus-continuity/blob/7cda34e81935683b83057ed3229dc19ed6e082d8/lib/events.js#L1742-L1743

However, in the case we are discussing here, the duplicate operation would be assigned to the same eventHash and all the other meta data would also be the same:
```
    "meta": {
        "eventHash": "wF291ySPW1Gor12zBS6MpTHfkMvQcqaUwVLLK1sWWuc=",
        "eventOrder": 0,
        "operationHash": "ni:///sha-256;pS-FYTJPXm-eNYsCdvvwhAZEIeO_DXFN4REwfj4K8Dw"
    }
``` 
This would lead to a violation of this unique index: https://github.com/digitalbazaar/bedrock-ledger-storage-mongodb/blob/6631f9f7b03e13782bcafdbcdcdbb0e66650e679/lib/index.js#L191-L192

The operation travels through this code path:

1. https://github.com/digitalbazaar/bedrock-ledger-consensus-continuity/blob/7cda34e81935683b83057ed3229dc19ed6e082d8/lib/operations.js#L62-L63
2. https://github.com/digitalbazaar/bedrock-ledger-storage-mongodb/blob/master/lib/ledgerOperationStorage.js#L28

Where duplicate errors are again ignored.  So a cursory review of the impacts of this issue indicate that no further action is required related to Continuity ledgers.

I think that in any case where it matters if the operation originated from Party A or Party B would involve there being a proof on the operation which would result in different `operationHash` values.

Furthermore,  even if a nonce were added to events, I can't think of any reason that it would be desirable to have two unique events referencing the same `operationHash`, and two copies of the operation that differ only in their meta data.

Case closed.
