### ISSUE TITLE
Structure of UpdateWebLedgerRecord

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-ledger-storage-mongodb#23]
Is this representation of a UpdateWebLedgerRecord accurate?

Any flexibility on this design?  I can access `CreateWebLedgerRecord` by doing a query on `operation.record.id`.  I was expecting that I would be able to pickup updates as well, but the structure here is completely different?  Can updates have a similar structure to create records?  Which involves changing `recordPatch` -> `record`, and `target` -> `id`

This would simplify querying and reduce the number of indexed fields with no apparent (to me) loss of fidelity.

sample from from: https://github.com/digitalbazaar/bedrock-ledger-storage-mongodb/blob/6631f9f7b03e13782bcafdbcdcdbb0e66650e679/test/mocha/mock.data.js#L115-L132
```
{
  '@context': config.constants.WEB_LEDGER_CONTEXT_V1_URL,
  type: 'UpdateWebLedgerRecord',
  recordPatch: {
    target: `https://example.com/events/a05bebf8-c966-427f-92f2-ff9060f4bd23`,
    sequence: 0,
    patch: [{
      op: 'add', path: '/endDate', value: '2017-07-14T23:30'
    }]
  },
  proof: {
    type: 'RsaSignature2018',
    created: '2017-05-10T19:47:13Z',
    creator: "https://bedrock.local:18443/consensus/continuity2017/voters/57565658-0d8a-4668-b734-e801aeaa6472#key",
    jws: "nlx8c9u...GqE/g=="
  }
}
```
## Proposal
```
{
  '@context': config.constants.WEB_LEDGER_CONTEXT_V1_URL,
  type: 'UpdateWebLedgerRecord',
  record: {
    id: `https://example.com/events/a05bebf8-c966-427f-92f2-ff9060f4bd23`,
    sequence: 0,
    patch: [{
      op: 'add', path: '/endDate', value: '2017-07-14T23:30'
    }]
  },
  proof: {
    type: 'RsaSignature2018',
    created: '2017-05-10T19:47:13Z',
    creator: "https://bedrock.local:18443/consensus/continuity2017/voters/57565658-0d8a-4668-b734-e801aeaa6472#key",
    jws: "nlx8c9u...GqE/g=="
  }
}
```

**Comment by dlongley** [comment]
The data model is correct and I don't think we should change it just to accommodate a local implementation indexing issue -- this would be a violation of a number of things.

Would it help if we added a database level record index field that uses `database.hash()` (like we do in many other places) that uses `record.id` when creating a record and `recordPatch.target` when updating one? Then we can query on that unified index?

**Comment by mattcollier** [comment]
Your suggestion sounds fine, `recordId` a good name for the root index field?

**Comment by dlongley** [comment]
`recordId` sounds good to me.
