### ISSUE TITLE
TODO: add index for `meta.consensus`

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-ledger-storage-mongodb#35]
https://github.com/digitalbazaar/bedrock-ledger-storage-mongodb/blob/master/lib/index.js#L45

@dlongley I think this may have been put in the wrong place.  This is setting up the indexes on the collection for the storage API.  There is no `meta.consensus` for this collection.

I want to confirm before removing.

**Comment by dlongley** [comment]
Seems like it was intended for something else, yes. Go ahead and remove.
