### ISSUE TITLE
Update this project to Mongo 3.5

### ISSUE THREAD

**Issue by aljones15** [digitalbazaar/bedrock-ledger-storage-mongodb#50]
It seems like we might want to upgrade this `bedrock-mongodb` version `^7.0.0`?

Check [insertOne](http://mongodb.github.io/node-mongodb-native/3.6/api/Collection.html#insertOne) API

- [x] ./lib/LedgerEventStorage.js:131:      const {event, meta} = (await this.collection.insertOne(
- [x] ./lib/index.js:104:  await database.collections.ledger.insertOne(record, database.writeOptions);
- [x] ./lib/LedgerBlockStorage.js:112:      insertedRecord = (await this.collection.insertOne(
- [x] ensure the `ops` is still there after the operation succeeds

Check [insertMany](http://mongodb.github.io/node-mongodb-native/3.6/api/Collection.html#insertMany) API
- [x] ./lib/LedgerEventStorage.js:158:          await this.collection.insertMany(chunk, {ordered: true});
- [x] ./lib/LedgerOperationStorage.js:47:        await this.collection.insertMany(

Check [find](http://mongodb.github.io/node-mongodb-native/3.6/api/Collection.html#find) calls:
- [x] update all `find` calls to `options.projection`
- [x] ./lib/LedgerEventStorage.js:201:    const records = await this.collection.find(query, projection)
- [x] ./lib/LedgerEventStorage.js:218:    const records = await this.collection.find(query, projection)
- [x] ./lib/LedgerEventStorage.js:288:    const cursor = await this.collection.find(query, projection)
- [ ] ./lib/LedgerEventStorage.js:309:    const count = await this.collection.find(query).count();
- [x] ./lib/LedgerEventStorage.js:375:    const cursor = await this.collection.find(query, projection)
- [ ] check if `sort`, `hint`, and `limit`
- [x] ./lib/LedgerEventStorage.js:409:    return await this.collection.find(query).count();
- [x] ./lib/LedgerEventStorage.js:424:    const cursor = await this.collection.find(query, projection)
- [ ] ./lib/LedgerOperationStorage.js:81:      return this.collection.find(query).explain({executionStats: true});
- [ ] Double check that `explain` is still valid
- [x] ./lib/LedgerBlockStorage.js:194:      block.eventHash = (await this.eventCollection.find(query, projection)
- [x] ./lib/LedgerBlockStorage.js:259:      const records = await this.eventCollection.find(query, projection)
- [x] ./lib/LedgerBlockStorage.js:303:    const records = await this.collection.find(query, projection)
- [ ] ./lib/LedgerBlockStorage.js:325:    const cursor = this.collection.find(query).project(projection)
- [x] ./lib/LedgerBlockStorage.js:362:    const [eventBlock = {}] = await this.collection.find(query, projection)

Check [findOne](http://mongodb.github.io/node-mongodb-native/3.6/api/Collection.html#findOne) calls:
- [x] Add projection to `options.projection`
- [x] ./lib/LedgerBlockStorage.js:149:    const record = await this.collection.findOne(query, projection);
- [x] ./lib/LedgerBlockStorage.js:181:    const record = await this.collection.findOne(query, projection);
- [x] ./lib/LedgerBlockStorage.js:218:    const record = await this.collection.findOne(query, projection);
- [x] ./lib/LedgerBlockStorage.js:246:    const record = await this.collection.findOne(query, projection);
- [x] ./lib/LedgerBlockStorage.js:280:    const record = await this.collection.findOne(query, projection);
- [x] ./lib/index.js:142:  const record = await database.collections.ledger.findOne(query, {});
- [x] pass options to `lib/index.js` line 142

Check [updateOne](http://mongodb.github.io/node-mongodb-native/3.6/api/Collection.html#updateOne) calls:
- [x] ./lib/LedgerEventStorage.js:511:    const result = await this.collection.updateOne(
- [x] ./lib/LedgerEventStorage.js:539:    const result = await this.collection.updateOne(filter, update);
- [x] ./lib/LedgerBlockStorage.js:439:    const result = await this.collection.updateOne(
- [x] ./lib/LedgerBlockStorage.js:468:    const result = await this.collection.updateOne(filter, update);

Check [aggregate](http://mongodb.github.io/node-mongodb-native/3.6/api/Collection.html#aggregate) calls:

- [x] ./lib/LedgerEventStorage.js:247:      return this.collection.aggregate([
- [x] ./lib/LedgerEventStorage.js:255:      return this.collection.aggregate([
- [x] ./lib/LedgerEventStorage.js:325:    const records = await this.collection.aggregate([
- [x] ./lib/LedgerOperationStorage.js:106:    const records = await this.collection.aggregate([

Change `collection.s.name` to `collection.collectionName`:
- [x] ./lib/LedgerEventStorage.js:233:    const operationCollectionName = this.operationStorage.collection.s.name;
- [x] ./lib/LedgerEventStorage.js:323:    const operationCollectionName = this.operationStorage.collection.s.name;
- [x] ./lib/LedgerOperationStorage.js:25:    this.eventCollectionName = eventCollection.s.name;

Update calls on `count` with [`countDocument`](http://mongodb.github.io/node-mongodb-native/3.6/api/Collection.html#countDocuments):

- [x] ./lib/LedgerOperationStorage.js:83:    const count = await this.collection.count(query);
- [x] ./lib/LedgerBlockStorage.js:89:    const eventCount = await this.eventCollection.count(
- [x] ensure no queries use deprecated terms: `$where`, `$near`, `$nearSphere`

**Comment by aljones15** [comment]
Test Status:

```js
  36 passing (8m)
  25 failing
```

```js
  16) Operation Storage API
       getRecordHistory API
         gets history with multiple CreateWebLedgerRecord operations:
 9) Event Storage API
       getMany
         returns a cursor using `blockHeight` parameter:
 6) Event Storage API
       get API
         should get event with given hash:
 3) Block Storage API
       update API
         should update block:
  2) Block Storage API
       get API
         should get consensus block with given ID:
     Uncaught MongoError: 'from' option to $lookup must be a string, but was type null
      at MessageStream.messageHandler (node_modules/mongodb/lib/cmap/connection.js:266:20)
      at MessageStream.EventEmitter.emit (domain.js:475:20)
      at processIncomingData (node_modules/mongodb/lib/cmap/message_stream.js:144:12)
      at MessageStream._write (node_modules/mongodb/lib/cmap/message_stream.js:42:5)
      at doWrite (_stream_writable.js:435:12)
      at writeOrBuffer (_stream_writable.js:419:5)
      at MessageStream.Writable.write (_stream_writable.js:309:11)
      at Socket.ondata (_stream_readable.js:728:22)
```

Possible False Negative (these tests might be failing for the right reasons):

```js
 14) Operation Storage API
       getRecordHistory API
         returns NotFoundError on an unknown recordId:

      Uncaught AssertionError: expected 'MongoError' to equal 'NotFoundError'
      + expected - actual

      -MongoError
      +NotFoundError
      
      at /home/liminal18/Programs/nodeJS/digital_bazaar/bedrock-ledger-storage-mongodb/test/mocha/35-operation-api.js:111:25
      at cb (util.js:196:39)
      at util.js:180:10
      at hidden (internal/errors.js:251:14)
      at processTicksAndRejections (internal/process/task_queues.js:81:21)

  15) Operation Storage API
       getRecordHistory API
         does not get history for an operation without consensus:

      Uncaught AssertionError: expected 'MongoError' to equal 'NotFoundError'
      + expected - actual

      -MongoError
      +NotFoundError
```

**Comment by aljones15** [comment]
test for this line:

```js
https://github.com/digitalbazaar/bedrock-ledger-storage-mongodb/blob/master/lib/LedgerEventStorage.js#L164
```

**Comment by dlongley** [comment]
This upgrade has occurred, closing.
